CREATE DATABASE `fundraise`;



CREATE TABLE `fundraise`.`USER` (
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `ADDRESS_LINE_1` VARCHAR(100) NOT NULL,
  `ADDRESS_LINE_2` VARCHAR(100) NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `ZIPCODE` INT(11) NOT NULL,
  `PHONE` VARCHAR(10) NOT NULL,
  `INTEREST` VARCHAR(45) DEFAULT NULL,
  `PHOTO` BLOB,
  PRIMARY KEY (`EMAIL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`CREDIT_CARD` (
  `CREDIT_CARD_NUMBER` VARCHAR(16) NOT NULL,
  `CVV` INT(3) NOT NULL,
  `EXPIRATION_MONTH` INT(2) NOT NULL,
  `EXPIRATION_YEAR` INT(2) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `CREDIT_CARD_NUMBER_UNIQUE` (`CREDIT_CARD_NUMBER` ASC),
  PRIMARY KEY (`EMAIL_ID`),
  CONSTRAINT `FK_CREDIT_CARD_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`FOLLOWER` (
  `FOLLOWER_EMAIL_ID` VARCHAR(45) NOT NULL,
  `FOLLOWED_EMAIL_ID` VARCHAR(45) NOT NULL,
  `FOLLOW_START_DATETIME` DATETIME NOT NULL,
  `FOLLOW_END_DATETIME` DATETIME NULL,
  PRIMARY KEY (`FOLLOWER_EMAIL_ID`, `FOLLOWED_EMAIL_ID`),
  CONSTRAINT `FK_FOLLOWER_USER_FOLLOWER_EMAIL_ID`
    FOREIGN KEY (`FOLLOWER_EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_FOLLOWER_USER_FOLLOWED_EMAIL_ID`
    FOREIGN KEY (`FOLLOWED_EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`CATEGORY`
(
  `CATEGORY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`PROJECT`(
 `PROJECT_ID` INT(11) NOT NULL AUTO_INCREMENT,
 `PROJECT_TITLE` VARCHAR(45) NOT NULL UNIQUE,
 `DESCRIPTION` VARCHAR(200) NOT NULL ,
 `DATE_TIME_CREATED` DATETIME NOT NULL ,
 `START_DATE` DATE NOT NULL ,
 `COMPLETION_DATE` DATE NULL,
 `PLANNED_COMPLETION_DATE` DATE NOT NULL ,
 `PHOTO` BLOB NULL,
 `VIDEO` VARCHAR(100) NULL,
 `STATUS` enum('FAILED','CAMPAIGNING', 'STARTED','COMPLETED') NOT NULL DEFAULT 'CAMPAIGNING',
 PRIMARY KEY (`PROJECT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`PROJECT_CATEGORY`(
 `PROJECT_ID` INT(11) NOT NULL ,
 `CATEGORY_ID` INT(11) NOT NULL ,
 PRIMARY KEY (`PROJECT_ID`,`CATEGORY_ID`),
 CONSTRAINT `FK_PROJECT_CATEGORY_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `fundraise`.`PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 CONSTRAINT `FK_PROJECT_CATEGORY_CATEGORY_CATEGORY_ID`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `fundraise`.`CATEGORY` (`CATEGORY_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`PROJECT_CAMPAIGN`(
 `PROJECT_ID` INT(11) NOT NULL UNIQUE,
 `FUND_START_DATE` DATE NOT NULL ,
 `FUND_END_DATE` DATE NOT NULL ,
 `MIN_FUND_GOAL` DOUBLE(20,2) NOT NULL ,
 `MAX_FUND_GOAL` DOUBLE(20,2) NOT NULL ,
 `STATUS` enum('IN_PROGRESS','COMPLETED', 'FAILED') NOT NULL DEFAULT 'IN_PROGRESS',
 CONSTRAINT FK_PROJECT_CAMPAIGN_PROJECT_PROJECT_ID
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`PROJECT_OWNERSHIP` (
  `PROJECT_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PROJECT_ID`,`EMAIL_ID`),
  CONSTRAINT `FK_PROJECT_OWNERSHIP_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`) REFERENCES `USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROJECT_OWNERSHIP_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`FUNDS` (
  `PROJECT_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `PLEDGED_MONEY` DOUBLE(20,2) NOT NULL,
  `DATETIME_PLEDGED` DATETIME NOT NULL,
  `TRANSACTION_DATETIME` DATETIME NULL,
  PRIMARY KEY (`PROJECT_ID`, `EMAIL_ID`),
  CONSTRAINT `FK_FUNDS_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE ,
  CONSTRAINT `FK_FUNDS_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `fundraise`.`PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`RATINGS` (
  `NUMBER_OF_STARS` DOUBLE(2,1) NOT NULL,
  `DATETIME_POSTED` DATETIME NOT NULL,
  `PROJECT_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EMAIL_ID`, `PROJECT_ID`),
  CONSTRAINT `FK_RATINGS_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `fundraise`.`PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE ,
  CONSTRAINT `FK_RATINGS_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`PROJECT_COMMENTS` (
  `PROJECT_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `DATE_TIME_POSTED` DATETIME NOT NULL,
  PRIMARY KEY (`PROJECT_ID`, `EMAIL_ID`,`DATE_TIME_POSTED`),
  CONSTRAINT `FK_PROJECT_COMMENTS_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `fundraise`.`PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROJECT_COMMENTS_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`PROJECT_LIKES` (
  `PROJECT_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `DATE_TIME_LIKED` DATETIME NOT NULL,
  PRIMARY KEY (`PROJECT_ID`,`EMAIL_ID`),
  CONSTRAINT `FK_PROJECT_LIKES_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`) REFERENCES `USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROJECT_LIKES_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`POST` (
  `POST_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `DATE_TIME_POSTED` DATETIME NOT NULL,
  `MULTIMEDIA` BLOB NULL,
  `TYPE` enum('AUDIO','IMAGE', 'VIDEO') NULL,
  PRIMARY KEY (`POST_ID`),
  CONSTRAINT `FK_POST_PROJECT_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID`)
    REFERENCES `fundraise`.`PROJECT` (`PROJECT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE ,
  CONSTRAINT `FK_POST_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`POST_COMMENTS` (
  `POST_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `DATE_TIME_POSTED` DATETIME NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`POST_ID`, `EMAIL_ID`,`DATE_TIME_POSTED`),
  CONSTRAINT `FK_POST_COMMENTS_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`)
    REFERENCES `fundraise`.`USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE ,
  CONSTRAINT `FK_POST_COMMENTS_POST_POST_ID`
    FOREIGN KEY (`POST_ID`)
    REFERENCES `fundraise`.`POST` (`POST_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `fundraise`.`POST_LIKES` (
  `POST_ID` INT(11) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `DATE_TIME_LIKED` DATETIME NOT NULL,
  PRIMARY KEY (`POST_ID`,`EMAIL_ID`),
  CONSTRAINT `FK_POST_LIKES_USER_EMAIL_ID`
    FOREIGN KEY (`EMAIL_ID`) REFERENCES `USER` (`EMAIL_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_POST_LIKES_POST_POST_ID`
    FOREIGN KEY (`POST_ID`) REFERENCES `POST` (`POST_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;